### ISSUE TITLE
XS::TCC 0.03 can't find Alien::TinyCC's libtcc.a on Windows.

### ISSUE THREAD

**Issue by aero** [run4flat/Alien-TinyCC#5]
Hi

Now, XS::TCC 0.03 uses Alien::TinyCC for a tcc copy instead of shipping sources.

I got the following error when building it on windows.

```
dmake.exe:  Error: -- `\strawberry-perl-5.16-32bit\perl\site\lib\auto\share\dist\Alien-TinyCC\libtcc.a' not found, and can't be made
```

On linux, libtcc.a is in ..../auto/share/dist/Alien-TinyCC/lib directory.
but on windows, libtcc1.a is in ....\auto\share\dist\Alien-TinyCC\lib directory and libtcc.a is in ....\auto\share\dist\Alien-TinyCC\libtcc directory.

Why the directory structures are different between linux and windows?

**Comment by run4flat** [comment]
This has been addressed in my latest commits, and a pull request for XS::TCC. There seem to be linker issues with both XS::TCC and C::TinyCompiler, but I'm not sure if that's Alien::TinyCC's fault.
